import {Router} from 'express'
import {requireAuth} from '../middleware/auth.js'
import {requirePermission,isAdminOrAbove} from '../lib/permissions.js'
import {ownScope} from '../lib/recordScope.js'
import {assertPeriodOpen} from './_guards.js'
import {fields,objectId,fail} from '../lib/attendance.js'
import Record from '../models/ManagementRecord.js'
import Employee from '../models/Employee.js'
const r=Router(),run=fn=>async(req,res,next)=>{try{await fn(req,res)}catch(e){next(e)}};r.use(requireAuth,requirePermission('management-payroll'))
r.patch('/:period/:id',run(async(req,res)=>{if(!isAdminOrAbove(req.user.role))throw fail(403,'التعديل للإدارة فقط');fields(req.body,['employee','streamer','tier','score','days','hours']);const period=objectId(req.params.period);await assertPeriodOpen(period);const employee=await Employee.findOne({_id:objectId(req.body.employee),dept:'management'});if(!employee)throw fail(404,'الموظف غير موجود');const data={employee:employee._id,streamer:String(req.body.streamer||'').trim()};for(const key of ['tier','score','days','hours']){data[key]=Number(req.body[key]??0);if(!Number.isFinite(data[key])||data[key]<0)throw fail(400,'قيمة رقمية غير صالحة')}if(!data.streamer||data.streamer.length>200||![1,2,3,4,5].includes(data.tier)||data.days>31||data.hours>744)throw fail(400,'راجع بيانات السجل');const result=await Record.findOneAndUpdate({_id:objectId(req.params.id),period},{$set:data},{new:true,runValidators:true});if(!result)throw fail(404,'السجل غير موجود');res.json(result)}))
r.get('/:period',run(async(req,res)=>{const period=objectId(req.params.period);res.json(await Record.find({period,...ownScope(req.user,'management')}).sort({createdAt:-1}).limit(10000).populate('employee','name email'))}))
r.post('/:period',run(async(req,res)=>{fields(req.body,['employee','streamer','tier','score','days','hours']);const period=objectId(req.params.period);await assertPeriodOpen(period);const employee=await Employee.findOne({_id:objectId(req.body.employee),dept:'management'});if(!employee)throw fail(404,'الموظف غير موجود');const data={};for(const key of ['tier','score','days','hours']){data[key]=Number(req.body[key]??0);if(!Number.isFinite(data[key])||data[key]<0)throw fail(400,'قيمة رقمية غير صالحة')}if(![1,2,3,4,5].includes(data.tier)||data.days>31||data.hours>744)throw fail(400,'راجع الأيام والساعات والفئة');const streamer=String(req.body.streamer||'').trim();if(!streamer||streamer.length>200)throw fail(400,'اسم الستريمر مطلوب');res.status(201).json(await Record.create({...data,period,employee:employee._id,userId:req.user._id,streamer}))}))
r.delete('/:period/:id',run(async(req,res)=>{if(!isAdminOrAbove(req.user.role))throw fail(403,'الحذف للإدارة فقط');const period=objectId(req.params.period);await assertPeriodOpen(period);const result=await Record.findOneAndDelete({_id:objectId(req.params.id),period});if(!result)throw fail(404,'السجل غير موجود');res.sendStatus(204)}));export default r
