export interface Report {key:string;title:string;period:string;columns:any[];rows:any[]}
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
export const safeName=(v:string)=>v.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,100)||'record'
export function saveFile(data:Blob,name:string){const url=URL.createObjectURL(data),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
export async function excelFile(report:Report){
 const ExcelJS=await import('exceljs'),book=new ExcelJS.Workbook(),sheet=book.addWorksheet(report.title.slice(0,31),{views:[{rightToLeft:true,state:'frozen',ySplit:1}]});sheet.columns=report.columns.map(c=>({header:c.label,key:c.key,width:22}));for(const r of report.rows)sheet.addRow(Object.fromEntries(report.columns.map(c=>[c.key,r[c.key]??''])));sheet.getRow(1).eachCell(c=>{c.font={bold:true,color:{argb:'FFFFFFFF'}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF1D2B49'}}});sheet.autoFilter={from:{row:1,column:1},to:{row:Math.max(1,sheet.rowCount),column:report.columns.length}};sheet.eachRow(row=>{row.alignment={vertical:'middle',wrapText:true};row.height=28});return new Blob([await book.xlsx.writeBuffer() as any],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})
}
export function payslipHtml(report:Report,row:any){
 const number=(v:any)=>Number(v||0).toLocaleString('en-US',{maximumFractionDigits:2}),usd=(v:any)=>'$'+Number(v||0).toFixed(2)
 return `<header style="background:#1c2b49;color:white;padding:28px 26px;border-bottom:3px solid #cda52a;display:flex;justify-content:space-between"><div><h1 style="margin:0 0 20px;font-size:24px">PAYSLIP</h1><small>Pay Period: ${esc(report.period)}</small></div><div style="text-align:right"><b>${esc(row.name)}</b><p style="font-size:10px">Employee Ref: ${esc(row.id.slice(-6))}</p></div></header><main style="padding:24px 26px"><div style="display:flex;gap:1px;margin-bottom:16px">${['days','hours','score'].map(k=>`<div style="flex:1;background:#f3f4f6;border-radius:7px;padding:15px;text-align:center"><small style="font-size:8px;letter-spacing:1px;color:#80889b">${k.toUpperCase()}</small><p style="font-size:16px;font-weight:800;margin:12px 0 2px">${number(row[k])}</p></div>`).join('')}</div>${[['SALARY','cash','#1c2b49'],['BONUS','bonus','#22964f'],['DEDUCTION','deduction','#ce3838']].map(([label,k,color])=>`<div style="background:#f3f4f6;border-radius:7px;padding:18px 14px;display:flex;justify-content:space-between;margin:12px 0"><b style="font-size:10px;color:#80889b;letter-spacing:1px">${label}</b><b style="color:${color}">${usd(row[k])}</b></div>${row[k+'Reason']?`<div style="margin:12px 14px 24px;font-size:11px;white-space:pre-wrap;overflow-wrap:anywhere"><span style="color:#80889b">Reason:</span><p dir="auto">${esc(row[k+'Reason'])}</p></div>`:''}`).join('')}<div style="background:#1c2b49;color:white;border-radius:7px;padding:14px 16px;margin-top:20px"><p style="display:flex;justify-content:space-between"><b style="font-size:10px;letter-spacing:1px">TOTAL (USD)</b><b>${usd(row.total)}</b></p><p style="display:flex;justify-content:space-between"><b style="font-size:10px;letter-spacing:1px">TOTAL (EGP)</b><b>EGP ${number(row.egp)}</b></p></div>${report.columns.filter(c=>c.custom).map(c=>`<p dir="auto">${esc(c.label)}: ${esc(row[c.key])}</p>`).join('')}</main>`
}
export async function pdfFile(report:Report,individual?:any){
 const [{jsPDF},{default:html2canvas}]=await Promise.all([import('jspdf'),import('html2canvas')]);const payslip=individual&&['streamers','name-rates'].includes(report.key),pdf=new jsPDF({compress:true,orientation:payslip?'portrait':'landscape',unit:'pt',format:payslip?[600,863]:'a4'}),root=document.createElement('div');root.style.cssText='position:fixed;left:-12000px;top:0;background:white;color:#1c2b49;font-family:Arial,sans-serif;width:'+(payslip?600:1120)+'px;';document.body.appendChild(root)
 try{
  const datasets=individual?[[individual]]:Array.from({length:Math.max(1,Math.ceil(report.rows.length/14))},(_,i)=>report.rows.slice(i*14,i*14+14));const groups=payslip?[report.columns]:Array.from({length:Math.max(1,Math.ceil((report.columns.length-1)/7))},(_,i)=>[report.columns[0],...report.columns.slice(1+i*7,1+(i+1)*7)]);let page=0
  for(const rows of datasets)for(const columns of groups){root.innerHTML=payslip?payslipHtml(report,individual):`<section dir="rtl" style="padding:30px"><h1 style="margin:0">TEMSAH GROUP | ${esc(report.title)}</h1><p>${esc(report.period)} · عدد السجلات: ${report.rows.length}</p><table style="border-collapse:collapse;width:100%;table-layout:fixed;font-size:12px"><thead><tr>${columns.map(c=>`<th style="background:#1c2b49;color:white;padding:12px;border:1px solid #dce0e8">${esc(c.label)}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr>${columns.map(c=>`<td style="padding:10px;border:1px solid #dce0e8;background:${i%2?'#f4f5f8':'white'};white-space:pre-wrap;overflow-wrap:anywhere">${esc(r[c.key])}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`;await document.fonts.ready;const canvas=await html2canvas(root,{scale:1.6,backgroundColor:'#ffffff',logging:false});const w=pdf.internal.pageSize.getWidth(),h=pdf.internal.pageSize.getHeight()-25,scale=w/canvas.width,sliceHeight=Math.floor(h/scale);for(let y=0;y<canvas.height;y+=sliceHeight){if(page++)pdf.addPage();const slice=document.createElement('canvas');slice.width=canvas.width;slice.height=Math.min(sliceHeight,canvas.height-y);slice.getContext('2d')!.drawImage(canvas,0,y,canvas.width,slice.height,0,0,canvas.width,slice.height);pdf.addImage(slice.toDataURL('image/png'),'PNG',0,0,w,slice.height*scale);pdf.setFontSize(8);pdf.text(String(page),w/2,pdf.internal.pageSize.getHeight()-9)}}return pdf.output('blob')
 }finally{root.remove()}
}
export async function zipFile(report:Report,progress:(n:number)=>void){const {default:JSZip}=await import('jszip'),zip=new JSZip();for(let i=0;i<report.rows.length;i++){const row=report.rows[i];zip.file(String(i+1).padStart(3,'0')+'-'+safeName(row.name||row.id)+'.pdf',await pdfFile(report,row));progress(i+1)}return zip.generateAsync({type:'blob',compression:'DEFLATE'})}
