import {Component,inject,effect} from '@angular/core'
import {CommonModule} from '@angular/common'
import {FormsModule} from '@angular/forms'
import {HttpClient} from '@angular/common/http'
import {firstValueFrom} from 'rxjs'
import {PayrollService} from '../core/payroll.service'
import {AuthService} from '../core/auth.service'
import {environment} from '../../environments/environment'
import {RowReportsService} from '../core/row-reports.service'
import {confirmAction} from '../core/confirm-dialog'
@Component({standalone:true,imports:[CommonModule,FormsModule],template:`<h1>سجل الإدارة</h1><p role="alert">{{error}}</p><form class="management-record-form" *ngIf="auth.can('management-payroll','write')" (ngSubmit)="add()"><label>الموظف<select name="employee" [(ngModel)]="form.employee" required><option value="">اختر موظفاً</option><option *ngFor="let p of payroll.managementEmployees()" [value]="p.id">{{p.name}}</option></select></label><label>اسم الستريمر<input name="streamer" [(ngModel)]="form.streamer" required maxlength="200"/></label><label>Tier<select name="tier" [(ngModel)]="form.tier"><option *ngFor="let t of [1,2,3,4,5]" [ngValue]="t">Tier {{t}}</option></select></label><label>Score<input name="score" type="number" min="0" [(ngModel)]="form.score"/></label><label>الأيام<input name="days" type="number" min="0" max="31" [(ngModel)]="form.days"/></label><label>الساعات<input name="hours" type="number" min="0" max="744" [(ngModel)]="form.hours"/></label><button [disabled]="busy||payroll.isPeriodLocked()" class="bg-gold-500 rounded p-3">{{editing ? "حفظ التعديل" : "إضافة للسجل"}}</button><button type="button" *ngIf="editing" (click)="editing='';form.streamer=''">إلغاء التعديل</button></form><div class="bg-white rounded-lg overflow-auto"><table class="w-full"><thead><tr><th>الموظف</th><th>الستريمر</th><th>Tier</th><th>Score</th><th>الأيام</th><th>الساعات</th><th>المكافأة EGP</th><th>الإجراءات</th><th>PDF</th></tr></thead><tbody><tr *ngFor="let r of rows"><td>{{r.employee?.name}}</td><td>{{r.streamer}}</td><td>{{r.tier}}</td><td>{{r.score}}</td><td>{{r.days}}</td><td>{{r.hours}}</td><td>{{payroll.settings().tierAmounts[$any(r.tier)]||0}}</td><td><button *ngIf="auth.isAdmin()" [disabled]="busy||payroll.isPeriodLocked()" (click)="edit(r)">تعديل</button><button *ngIf="auth.isAdmin()" [disabled]="busy||payroll.isPeriodLocked()" (click)="remove(r._id)">حذف</button></td><td class="pdf-cell"><button (click)="pdf(r._id)" [disabled]="busy" class="row-pdf">↓ PDF</button></td></tr><tr *ngIf="!rows.length&&!busy"><td colspan="9">لا توجد سجلات لهذه الفترة</td></tr></tbody></table></div>`})
export class ManagementLogComponent{reports=inject(RowReportsService);editing='';edit(r:any){this.editing=r._id;this.form={employee:r.employee?._id||r.employee,streamer:r.streamer,tier:r.tier,score:r.score,days:r.days,hours:r.hours}}async pdf(id:string){this.busy=true;try{await this.reports.pdf('management-log',this.payroll.currentPeriodId()!,id)}catch(e:any){this.error=e.message||'تعذر تصدير PDF'}finally{this.busy=false}}payroll=inject(PayrollService);auth=inject(AuthService);http=inject(HttpClient);rows:any[]=[];error='';busy=false;form={employee:'',streamer:'',tier:1,score:0,days:0,hours:0};api=environment.apiUrl+'/management-records/';constructor(){effect(()=>{const id=this.payroll.currentPeriodId();if(id)void this.load(id)})}async load(id:string){try{this.rows=await firstValueFrom(this.http.get<any[]>(this.api+id));this.error=''}catch(e:any){this.error=e.error?.message||'تعذر تحميل السجل'}}async add(){const id=this.payroll.currentPeriodId();if(!id||this.busy)return;this.busy=true;try{await firstValueFrom(this.editing?this.http.patch(this.api+id+'/'+this.editing,this.form):this.http.post(this.api+id,this.form));this.editing='';this.form.streamer='';await this.load(id);await this.payroll.loadPeriodData(id)}catch(e:any){this.error=e.error?.message||'تعذر حفظ السجل'}finally{this.busy=false}}async remove(id:string){if(!await confirmAction('حذف هذا السجل؟'))return;this.busy=true;try{await firstValueFrom(this.http.delete(this.api+this.payroll.currentPeriodId()+'/'+id));await this.load(this.payroll.currentPeriodId()!);await this.payroll.loadPeriodData(this.payroll.currentPeriodId()!)}catch(e:any){this.error=e.error?.message||'تعذر الحذف'}finally{this.busy=false}}}
