import {Component,OnInit,OnDestroy,inject} from '@angular/core'
import {CommonModule} from '@angular/common'
import {FormsModule} from '@angular/forms'
import {HttpClient} from '@angular/common/http'
import {ActivatedRoute,Router} from '@angular/router'
import {firstValueFrom} from 'rxjs'
import {AuthService} from '../core/auth.service'
import {environment} from '../../environments/environment'
@Component({standalone:true,imports:[CommonModule,FormsModule],template:`<section class="inbox"><header><button (click)="router.navigateByUrl(auth.landingPage())">الرئيسية</button><h1>{{conversation?'محادثة المهمة':'الإشعارات والمحادثات'}}</h1><button *ngIf="conversation" (click)="back()">← رجوع للقائمة</button></header><p role="alert" class="page-error" *ngIf="error">{{error}}</p><ng-container *ngIf="!conversation"><button class="inbox-row" *ngFor="let row of rows" (click)="open(row._id)"><strong>{{row.text||'مهمة بصورة'}}</strong><span>{{row.assignedTo?.fullName||row.assignedTo?.name}} · {{row.status}}</span><small>{{row.updatedAt|date:'short'}}</small></button><p *ngIf="!rows.length">لا توجد محادثات</p><div class="pager"><button [disabled]="page<=1||busy" (click)="page=page-1;load()">السابق</button><span>{{page}} / {{pages}}</span><button [disabled]="page>=pages||busy" (click)="page=page+1;load()">التالي</button></div></ng-container><ng-container *ngIf="conversation"><h2>{{conversation.task.text}}</h2><img class="chat-image" *ngIf="conversation.task.image?.url" [src]="conversation.task.image.url" alt="صورة المهمة"/><div class="chat-list"><article *ngFor="let m of conversation.rows" class="chat-bubble" [class.mine]="m.sender?._id===auth.user()?.id"><b>{{m.sender?.fullName||m.sender?.name}}</b><p>{{m.text}}</p><a *ngIf="m.image?.url" [href]="m.image.url" target="_blank" rel="noopener"><img class="chat-image" [src]="m.image.url" alt="صورة مرفقة" loading="lazy"/></a><small>{{m.createdAt|date:'short'}}</small></article></div><div class="pager"><button [disabled]="messagePage<=1||busy" (click)="messagePage=messagePage-1;open(conversation.task._id,false)">الأحدث</button><span>{{messagePage}}</span><button [disabled]="messagePage*40>=conversation.total||busy" (click)="messagePage=messagePage+1;open(conversation.task._id,false)">الأقدم</button></div><form *ngIf="canSend" (ngSubmit)="send()" class="chat-compose"><textarea [(ngModel)]="draft" name="draft" maxlength="4000" placeholder="اكتب رسالتك" aria-label="رسالتك"></textarea><label>صورة اختيارية (حتى 3 MB)<input type="file" accept="image/png,image/jpeg" (change)="choose($event)"/></label><span>{{image?.name}}</span><button [disabled]="busy||(!draft.trim()&&!image)">إرسال</button></form></ng-container></section>`})
export class NotificationsComponent implements OnInit,OnDestroy{
 http=inject(HttpClient);auth=inject(AuthService);route=inject(ActivatedRoute);router=inject(Router);rows:any[]=[];conversation:any;page=1;total=0;messagePage=1;draft='';image:any=null;busy=false;error='';poll:any;api=environment.apiUrl+'/conversations';get pages(){return Math.max(1,Math.ceil(this.total/20))}get canSend(){const t=this.conversation?.task,id=this.auth.user()?.id;return this.auth.isAdmin()||t?.assignedTo?._id===id||t?.userId?._id===id}
 ngOnInit(){const id=this.route.snapshot.queryParamMap.get('task');if(id)void this.open(id);else void this.load();this.poll=setInterval(()=>{if(!this.busy){if(this.conversation)void this.open(this.conversation.task._id,false);else void this.load()}},15000)}ngOnDestroy(){clearInterval(this.poll)}
 async load(){try{const r=await firstValueFrom(this.http.get<any>(this.api,{params:{page:this.page}}));this.rows=r.rows;this.total=r.total;this.error=''}catch(e:any){this.error=e.error?.message||e.message}}
 async open(id:string,reset=true){if(reset)this.messagePage=1;try{this.conversation=await firstValueFrom(this.http.get(this.api+'/'+id,{params:{page:this.messagePage}}));this.error=''}catch(e:any){this.error=e.error?.message||e.message}}
 back(){this.conversation=null;void this.router.navigate([], {queryParams:{}});void this.load()}
 async choose(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];input.value='';if(!file)return;if(file.size>3*1024*1024||!['image/png','image/jpeg'].includes(file.type)){this.error='اختر صورة PNG أو JPG حتى 3 MB';return}const base64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});this.image={name:file.name,base64}}
 async send(){if(this.busy||!this.canSend)return;this.busy=true;try{await firstValueFrom(this.http.post(this.api+'/'+this.conversation.task._id,{text:this.draft,image:this.image}));this.draft='';this.image=null;await this.open(this.conversation.task._id)}catch(e:any){this.error=e.error?.message||e.message}finally{this.busy=false}}
}
